version: '3'

services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres-12345
      POSTGRES_DB: the-tourney
    volumes:
      - ~/postgres-data:/var/lib/postgresql/data